### ISSUE TITLE
Speichern von Schichten in der Zukunft

### ISSUE THREAD

**Issue by mimischi** [mimischi/django-clock#101]
Der aktuelle Check erlaubt es nicht, dass Schichten in der Zukunft gespeichert werden - was auch Sinn macht.
Trotzdem werden alle Schichten um 5 Minuten gerundet. Gerade erst beendete Schichten (über die Frontpage) lassen sich so also nur bearbeiten, wenn man a) maximal 5 Minuten wartet oder b) die Endzeit um 5 Minuten verkleinert.

**Comment by sheepyhollow** [comment]
Wenn das nur im Bereich +5 min from now passiert, könnte man da 'ne intelligente Ausnahme machen?

**Comment by sheepyhollow** [comment]
Was war denn eigentlich mit dem Thema "Schichten vorausplanen"? Das wäre ein future feature.
Hatten wir mal von geredet - z.B. Präsenzzeiten (regelmäßige Tutorien) schon im Vorhinein (fürs ganze Semester) einzutragen. Wäre aber ein Addon für die Ideen-Kiste - Du hattest da einen Cron-Job vorgeschlagen. Man könnte für sowas aber auch den Zukunfts-Check umgehen.

**Comment by sheepyhollow** [comment]
Können wir dieses Issue nicht zugunsten von #13 schließen?

**Comment by mimischi** [comment]
Wird automatisch geschlossen, sobald PR #463 gemerged wird :)
