### ISSUE TITLE
Auto-Logoff

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#14]
Viele Seiten mit Login beenden die Session nach Zeitpunkt x (nicht die Shift, nur die Session) aus Sicherheitsgründen. Ist bestimmt eingebaut und steht auf 0 - nur, dass es nicht vergessen wird.

**Comment by mimischi** [comment]
Bleibt die Frage, ob man dem User so hinterher laufen muss? Aber ja, das wäre möglich. Du meinst explizit ein Logout nach X Minuten Inaktivität (also keinem rum klicken auf der Seite).

**Comment by sheepyhollow** [comment]
Man ist es einfach so gewohnt... 

ABER - da ich mich ja zum pausieren/ausclocken nicht unbedingt wieder neu anmelden will... 

...wäre ich für lassen, wie es ist (kein zwangs-Logout)

**Comment by mimischi** [comment]
Das stimmt allerdings. User sollen eingeloggt bleiben, sonst sinkt auf Dauer die Usability.
