### ISSUE TITLE
feat-req (für später): Shiftlist direkt editieren

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#16]
Nicht ein Extra-Fenster öffnen, sondern direkt in die Tabelle schreiben.

Erfordert offenbar AjAX und eilt auch nicht.

**Comment by mimischi** [comment]
Ist mittlerweile fraglich, ob wir das machen werden. Eventuell ist es für die Desktop-Version wünschenswert, aber auf keinen Fall für die mobile Version. Die Weiterleitung zu einer neuen Seite ist nicht so verkehrt.
