### ISSUE TITLE
feat-req: Shift project

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#17]
Freitext-Feld, um Shifts nach (selbst gewählten) Aufgaben zu trenne, also z.B. unterhalb eines Contracts verschiedene Projekte zu trennen.

Das wäre auch ein nettes Ding für die Charts

**Comment by mimischi** [comment]
Sprich anstatt des Notiz-Feldes ein extra Projekt-Feld? Die Projekte werden auch nicht innerhalb verschiedener Verträge geteilt, sondern für jeden Vertrag muss man eigene Projekte anlegen?

**Comment by sheepyhollow** [comment]
Also Notizen sind generell gut, um Dinge zu notieren - z.B. auch, was man (im Detail) gemacht hat. Dafür braucht es ein "großes" Freitext-Feld.

Ich fände aber ein optionales (zusätzliches) kurzes Projektfeld gut, in dem man z.B. "Lernbar", "Clock", "OLAT" etc. reinschreiben kann. Müssen auch keine vorher definierten Projekte sein, aber etwas, wonach ich filtern und sortieren kann (und vllt. auch in Charts anzeigen kann)

**Comment by sheepyhollow** [comment]
Natürlich würde das dann auf ein zweites Feld unter dem Contract-Dropdown hinauslaufen... hmm..... Trotzdem nicht uninteressant.

**Comment by mimischi** [comment]
Wie ist denn die Meinung noch hierzu, ist das noch nötig oder reicht das aktuelle Kommentarfeld? Das erfüllt ja genau diese Aufgabe eigentlich.

**Comment by sheepyhollow** [comment]
ja - aber ich kann z.B. nicht im (noch nicht existierenden Dashbord/Analysetool) nach diesen Keywords sortieren. Wenn ich z.B. frage: wie lange hast Du (unter einem Contract) für Projekt A gearbeitet, wieviel für Projekt B, wieviel für...

Wäre es denn eine Lösung, wenn man einfach ein weiteres Kommentarfeld an jede Shift hängt und "Keyword" nennt? Halte ich nach wie vor für sinnvoll (unter dem Aspekt der Analyse). Evtl. auch als zukünftiges Feature, wenn die Analyse erstmal läuft.

Als kleines Extra könnte man ja das anlegen von Projekten implizit machen. D.h. ich beginne mit Freitext, bekomme aber meine bereits eingegebenen Keywords als Dropdown angeboten - so wie autofill nur serverseitig.

**Comment by mimischi** [comment]
Als Lesezeichen für mich: http://django-tagging.readthedocs.io/en/develop/

**Comment by mimischi** [comment]
Lesezeichen 2: https://sean.is/poppin/tags
