### ISSUE TITLE
Startbildschirm

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#21]
Sind Startbildschirme nicht sowas von 2000er?

Ich finde es unergonomisch, wenn das Login erst auf Seite 2 ist. Schönes Logo hin oder her.

**Comment by mimischi** [comment]
Theoretisch bleibt man ja erstmal eingeloggt und muss kommt deswegen direkt ohne Umwege zum Dashboard. Eigentlich haben das auch alle modernen Seiten so, dass man erstmal auf einer Info-Seite (muss noch gemacht werden) landet, bevor man zum Login kommt.

**Comment by mimischi** [comment]
Also heutzutage finden sich solche Startseiten eigentlich überall. Ein neuer User sollte zuerst einen Einblick bekommen, was der Service eigentlich kann und macht. Ich finde es eher schlecht, wenn man so ziemlich keine Information findet und sich direkt für irgendwas 'dubioses' registrieren soll.

Für die Zukunft denke ich an so ein Carousel (http://getbootstrap.com/examples/carousel/), damit man auch ein paar weitere Unterseiten mit Informationen füttern kann.
