### ISSUE TITLE
Schichten nachtragen

### ISSUE THREAD

**Issue by chgad** [mimischi/django-clock#214]
Beim Nachtragen von Schichten, wenn man ein Zeichen in dem Vorgegebenen feld löschen willst mit der "Entf" Taste wird das ganze feld gecleared. Sollte vielleicht geändert werden, sehr nervig.

**Comment by sheepyhollow** [comment]
hab ich auch schon bemängelt, liegt aber am Datepicker, wenn ich mich recht erinnere. Könnte man auch in dessen Thread schieben?

**Comment by mimischi** [comment]
Der [DateTimePicker](https://github.com/Eonasdan/bootstrap-datetimepicker) hatte damals extrem viele Bugs, wodurch ich einiges an Funktionalitäten wieder ausgeschaltet habe. Wollte mal schauen, ob da das meiste gefixt ist mittlerweile.

Auf der [Demo-Seite](http://eonasdan.github.io/bootstrap-datetimepicker/) findet man recht viel von der schicken Funktionalität.

**Comment by mimischi** [comment]
Fixed a711897b3fbbe07a44084ad3d430248f833308a3.
