### ISSUE TITLE
Sammlung an Bugs...

### ISSUE THREAD

**Issue by svenk** [mimischi/django-clock#231]
... die ich im Juli gesammelt habe und seit dem nie gepostet. Daher jetzt hier als liste:

- [ ] neuer vertrag: stundenzahl pro was? (monat!)
- [ ] login auch mit email wäre cool
- [ ] Verträge können nicht mehr als 80 Stunden im Monat umfassen! - doch! bei festen verträgen etwa
- [ ] `[Clock] Please Confirm Your E-mail Address` -- falscher Absender (clock@idiotism.us)
- [x] Verträge auswählbar aber dann keine aktion möglich
- [x] Exportieren-button geht auf smartphone nicht

Kann sein dass da inzwischen einiges gefixt wurde. War auch alles etwas knapp aufgeschrieben aufm Smartphone.

**Comment by mimischi** [comment]
Bock auf paar Pull requests? Anleitung zum lokalen Installieren per Docker stehen ja in der [README](https://github.com/mimischi/django-clock#anleitung)!

Aber sind tatsächlich nur Kleinigkeiten. Zum Punkt 'Export geht nicht auf Smartphones': merke gerade, dass man auch den 'Schicht hinzufügen' Button nicht auf dem Smartphone klicken kann. Wahrscheinlich irgendein CSS-Bug..

**Comment by mimischi** [comment]
Export geht jetzt auf allen Displaygrößen dank 86742117ccf1283a848bd2d8d3182a8797d5605f.
Habe auch deinen Kommentar mal etwas formatiert. Was genau meinst du mit "Verträge auswählbar aber dann keine aktion möglich"? Konnte man keine der Buttons drücken?

**Comment by mimischi** [comment]
Outdated. Will be sorted out in future deployments.
