### ISSUE TITLE
Bug beim Einstellen der Endzeit einer Schicht

### ISSUE THREAD

**Issue by chgad** [mimischi/django-clock#336]
Ich habe das Problem, dass wenn ich eine Schicht an lege und die Endzeit festlegen will, dass der DatePicker mich nicht das Datum Anklicken lässt, welches ich möchte sondern auf dem verharrt das aktuell ist (der jeweilige Tag an dem ich es erstelle).

**Comment by mimischi** [comment]
Welchen Browser nutzt du denn? Kann es gerade in Firefox nicht nachvollziehen
