### ISSUE TITLE
Überlappen von Schichten

### ISSUE THREAD

**Issue by chgad** [mimischi/django-clock#464]
Wie von @sheepyhollow in #461 erwähnt ist das lösen von Schicht Überlappungen nicht zu vermeiden und die Lösung nicht Tirvial. Dieses Issue soll abgesondert von dem eben genannten als Diskussionsoberfläche dienen.

Ziel ist es zu klären:
- [x]  Wann können Überlappe eintreten ?

- [x]  Gibt es Überlapp fälle die man dynamisch lösen kann ?
- [x]  Wann sollen die Überlappe vom User geklärt werden ?
... to be continued.

**Comment by mimischi** [comment]
PR #463 ist schon in Vorbereitung, aber der Überlapp-Check ist aktuell noch drin, genauso wie im Live-System.

Aktuell gibt es nur ganz stupide die Meldung, dass es Schichten gibt, die mit der jetztigen Überlappen. Wir könnten aber auch die genauen Schichten auflisten (mit Details zu Start/Ende + Link) und den User bitten eins von beiden zu korrigieren. Wahrscheinlich würde auch vorerst die Anzeige reichen, mit welcher Schicht die aktuelle Eingabe überlappt und was die genauen Daten sind. Dadurch könnte der User das Ganze fix visuell lösen. Aktuell muss man sich durch das System klicken, was nicht ganz förderlich ist.

**Comment by sheepyhollow** [comment]
Hm... nach welchem Szenario gibt es Überlappungen von Schichten *eines Vertrags*? Beim Stechen kann's eigentlich nicht passieren (oder?). Also passiert es nur, wenn ich eine Schicht manuell nachtrage. Dann sollte das eigentlich schon während des Eingebens Alarm schlagen.

Was den Überlapp von Schichten *eines anderen Vertags* angeht, geht das natürlich nicht (man kann ja für Arbeitszeit nicht doppelt bezahlt werden). Das scheint mir das etwas kniffligere Szenario zu sein - sollte aber beim Stechen auch nicht auftreten können, da ich ja erst eine aktive Schicht beenden muss und dann (unter einem neuen Vertrag) neu stechen muss.

Natürlich können die Randbedingungen (forgotten shifts) das ein oder andere Artefakt erzeugen, aber  eigentlich keinen Überlapp, oder?

**Comment by mimischi** [comment]
> Hm... nach welchem Szenario gibt es Überlappungen von Schichten eines Vertrags? Beim Stechen kann's eigentlich nicht passieren (oder?). Also passiert es nur, wenn ich eine Schicht manuell nachtrage. Dann sollte das eigentlich schon während des Eingebens Alarm schlagen.

Korrekt.

> Was den Überlapp von Schichten eines anderen Vertags angeht, geht das natürlich nicht (man kann ja für Arbeitszeit nicht doppelt bezahlt werden). Das scheint mir das etwas kniffligere Szenario zu sein - sollte aber beim Stechen auch nicht auftreten können, da ich ja erst eine aktive Schicht beenden muss und dann (unter einem neuen Vertrag) neu stechen muss.

Wenn ich mich richtig erinnere hatten wir das schon besprochen: wo ein User auf dem analogen Stundenzettel bescheißen kann, sollten wir ihn nicht davon aufhalten dies auch bei der digitalen Version zu tun.
Wir können das natürlich checken, aber müssen wir das? Natürlich kann immer nur eine Schicht "gestochen" sein und damit aktuell laufen -- hier gibt es dann keine Überschneidungen (außer ich füge manuell eine Schicht hinzu, die sich mit der aktuellen überschneidet).

Ich denke wenn wir den Usern direkt eine Benachrichtigung bezüglich des Überlapps anzeigen sollte das schon ganz gut sein. Muss nur klug gelöst werden:

1. User versucht manuell eine Schicht A hinzuzufügen.
2. Diese Schicht überlappt sich mit Schicht B.
3. Clock zeigt dem User eine Benachrichtigung "Zeiten überlappen sich mit Schicht B. <Klicke hier zum Anpassen der Schicht B.>".
3a. User passt Schicht B an. Beim aktualisieren wird erneut das vorherige Formular mit den Daten von Schicht A geladen, welches nun weiter angepasst / gespeichert werden kann.
3b. User passt Schicht A an und speichert diese sofort. Schicht B muss also nicht angepasst werden.

Wenn ich es richtig sehe, kann Fall `3a` mit Hilfe von [Django Sessions](https://docs.djangoproject.com/en/2.0/topics/http/sessions/) gelöst werden.

**Comment by mimischi** [comment]
Ich denke, dass das Ganze relativ leicht zu implementieren ist (aktuell ist es ja schon zu Teilen implementiert). Allerdings gibt es hier noch einige Einschränkungen, die wir vorher klären sollten:

1. Die eingetragenen Zeiten werden aktuell auf die nahsten 5 Minuten auf-/abgerundet. Dadurch könnte es zu Kollisionen kommen.
2. Was solll passieren, wenn eine Schicht geplant wurde (11.00 - 13.00) und am selben Tag per Stechuhr gearbeitet wird (08.00 - 12.00). Dann müsste das Ausstechen verboten werden bzw. die Schicht eben beim beenden um 11.00 enden. Ansonsten gibt es einen Konflikt.

Was denkt ihr @chgad @sheepyhollow?

**Comment by sheepyhollow** [comment]
zu 1.) Welche Gründe hatte das 5-min-grid? Es ging darum, beim clocken zu kleine Einheiten zu vermeiden, oder? Müssen wir diese Einschränkung beibehalten?Bzw. was wäre ein Szenario, bei dem eine solche Kollision auftritt?

Könnte man alternativ Kollisionen in der 5-min-range (kann man ja prüfen) automatisch zwischen den Schichten verhandeln lassen? D.h. im Falle eines Überlapps von max 5 min wird z.B. die früher begonnene Schicht so weit gekürzt, dass der Überlapp vermieden wird?

zu 2.)

**Comment by mimischi** [comment]
> zu 1.) Welche Gründe hatte das 5-min-grid? Es ging darum, beim clocken zu kleine Einheiten zu vermeiden, oder? Müssen wir diese Einschränkung beibehalten?

Ich weiß gar nicht mehr warum wir das so etabliert haben. Eventuell hat es irgendwie damit zu tun, dass die mindest Länge einer Schicht auch 5 Minuten beträgt - das sollten wir wahrscheinlich dementsprechend beibehalten.

> Könnte man alternativ Kollisionen in der 5-min-range (kann man ja prüfen) automatisch zwischen den Schichten verhandeln lassen? D.h. im Falle eines Überlapps von max 5 min wird z.B. die früher begonnene Schicht so weit gekürzt, dass der Überlapp vermieden wird?

Kann man tun. Wollen wir das so festhalten?

> In zwei unterschiedlichen Contracts wird die Entscheidung schwieriger, ich würde aber dennoch bei dem Modell bleiben und den User beim Ausstechen informieren ("Du hattest von X-Y eine geplante Schicht. Deine vorherige Schicht (begonnen um ... Uhr) wurde daher beendet.")

Ich würde den User ja direkt benachrichtigen, wenn die aktuell gestochene Schicht einen überlapp erzeugt (sprich: das System sticht automatisch aus, wodurch niemals ein Überlapp geschieht).

> Deluxe-Variante: Das System merkt, dass ein planned vs. manual Konflikt vorliegt und bietet dem User eine Entscheidung an, welche Schicht gewinnt (siehe 3a), also quasi die geplante Schicht zu entfernen oder diese von der manuellen Schicht überschreiben zu lassen.

Zukunftsmusik!

**Comment by chgad** [comment]
Meine Gedanken dazu:

> Was solll passieren, wenn eine Schicht geplant wurde (11.00 - 13.00) und am selben Tag per Stechuhr gearbeitet wird (08.00 - 12.00). Dann müsste das Ausstechen verboten werden bzw. die Schicht eben beim beenden um 11.00 enden. Ansonsten gibt es einen Konflikt.

Gestochene Schicht > geplante Schicht. Ganz simple. Wenn live gestochen wird und die zu speichernde Schicht mit einer geplanten schicht kollidiert wird die geplante gelöscht und die gestochene gespeichert.

> Könnte man alternativ Kollisionen in der 5-min-range (kann man ja prüfen) automatisch zwischen den Schichten verhandeln lassen? D.h. im Falle eines Überlapps von max 5 min wird z.B. die früher begonnene Schicht so weit gekürzt, dass der Überlapp vermieden wird?

Wann soll das denn passieren ? Kann mir das nur bei "Cross Contract Relations" vorstellen, also selten (?) .

Generell würde ich das stechen Session-based umsetzen. D.h. ich starte eine Schicht auf der Website (Session angelegt) arbeite etwas, und wenn ich die Seite schließe (Session beendet) wird die Schciht beendet und gespeichert. Bei einer App anwendung müsste es etwas anders aussehen aber da habe ich etwas ähnliches gesehen. Stechen der Schicht in der App erstellt einen Sessiontoken in der Api für den User, dieser Token repräsentiert eine aktive Appsession, welche "geschlossen werden muss" (bzw. gecloned werden sollte --> fancy stuff) sobald eine Browsersession geöffnet wird.

**Comment by mimischi** [comment]
> Gestochene Schicht > geplante Schicht. Ganz simple. Wenn live gestochen wird und die zu speichernde Schicht mit einer geplanten schicht kollidiert wird die geplante gelöscht und die gestochene gespeichert.

Das widerspricht nun @sheepyhollow :)

> Generell würde ich das stechen Session-based umsetzen. D.h. ich starte eine Schicht auf der Website (Session angelegt) arbeite etwas, und wenn ich die Seite schließe (Session beendet) wird die Schciht beendet und gespeichert.

Der Gag an der _aktuellen_ Funktionsweise (Session unabhängig; gestartete Schichten werden direkt in der Datenbank angelegt) ist: starte ich meine Schicht am HiWi-PC im Büro und vergesse mich auszustechen, kann ich das unterwegs vom Smartphone/zu Hause am PC/von jedem Rechner weltweit korrigieren.

**Comment by sheepyhollow** [comment]
> Das widerspricht nun @sheepyhollow :)

Naja, wir können auch 'ne Münze werfen. Ich habe halt angenommen, dass man beim live-Stechen eher nen Fehler macht als beim bewussten Eintragen einer Schicht

> Kann mir das nur bei "Cross Contract Relations" vorstellen, also selten (?)
Nicht sicher, ob die so selten vorkommen.

**Comment by mimischi** [comment]
1. Prioritäten-Thematik

Wir könnten natürlich den User auffordern auszuwählen, was er in dem Fall machen will.

> **Achtung!** Die aktuell gestochene Schicht kollidiert mit einer schon gespeicherten Schicht. Du hast nun vier Möglichkeiten:
> 1. Aktuell gestochene Schicht behalten, gespeicherte Schicht löschen.
> 2. Gespeicherte Schicht behalten, gestochene Schicht löschen.
> 3. Gestochene Schicht so beenden, dass sie nicht mit der gespeicherten überlappt.
> 4. Gespeicherte Schicht anpassen, dass sie nicht mit der gestochenen überlappt.

Das könnte dann z.B. beim ausstechen angezeigt werden und der User _muss_ das Ganze erledigen bevor er das System weiter nutzen kann (Zwangsumleitung oder so etwas).

**Comment by mimischi** [comment]
Ich hab die Diskussion hier mal in zwei Flowcharts zusammengefasst. 

### Schicht starten
![begin_shift](https://user-images.githubusercontent.com/1052860/35482865-3f2999ac-043b-11e8-9a9e-274fbeba6ff5.png)

### Schicht beenden
![finish_shift](https://user-images.githubusercontent.com/1052860/35482868-4c7254be-043b-11e8-8c81-541493374ce1.png)

Die gelbe Notiz im letzten Bild ist ganz interessant: sollen wir beim Beenden der Schicht darauf achten, ob diese zu lang ist? Sprich, ab 6h muss ein User bis zu 30 Minuten Pause einlegen (bei 6h10m = 10 min Pause; 6h totale Arbeitszeit). Da wir das gesamte Pausensystem entfernen und Pausen effektiv nur als "Lücke zwischen zwei Schichten am selben Tag" definiert sind, müssen wir solche langen Schichten auseinander ziehen.

Falls wir das tun, muss vorher geschaut werden, ob es zu einem Überlapp mit einer schon vorhandenen Schicht kommt. Das ist aktuell nicht im Diagramm drin.

Die zugehörige Repository ist [hier](https://github.com/mimischi/clock-planning).

**Comment by sheepyhollow** [comment]
Erst nochmal zu den "4 Choices" - ich finde, das sind zu viele und es ist verwirrend, weil sich die Wahlmöglichkeiten auch sehr ähnlich lesen.
Ich fände es gut, wenn wir das auf 2 Choices reduzieren können - oder wir behalten die ersten beiden und fügen eine Option `Do magic...` hinzu, die den Konflikt löst (und natürlich dann mitteilt, wie).

Für die Optionen 3 & 4 würde ich eher der Argumentation von @chgad folgen, dass die gestochene Schicht gewinnen sollte, also eher Option 4 bevorzugen. Aber wir können auch immer auf die manuellen Schichteinstellungen verweisen. Also nach dem Motto `Magic worked! [von...bis] Du kannst diese Buchungen von Hand anpassen [link].`

Die Flowcharts sind super! Die müssen in die Doku... :smile:

Ich stimme zu, dass der Pausencheck beim Export gemacht wird. Wir müssen bei allem Mitspracherecht bedenken, dass nur kleine Zahl von Usern daran interessiert sein wird, hier minutengenau abzurechnen. Die meisten werden froh sein, wenn irgendwas Plausibles rauskommt, also sollten wir nicht zu viele Sonderfälle berücksichtigen bzw. zu viele Möglichkeiten geben. Drum machen wir uns diese Gedanken ja... Aber vielleicht müssen wir noch ein paar Meinungen mehr dazu hören?

Zu den Pausen... "fair" wäre es, die Schicht zu teilen, eine Pause einzufügen und die 2. Hälfte um die Pause zu schieben. Arbeitsrechtlich müsste die Schicht geteilt und die Pausenzeit gelöscht werden, oder? :wink:

**Comment by mimischi** [comment]
> Also nach dem Motto Magic worked! [von...bis] Du kannst diese Buchungen von Hand anpassen [link].
Sollten wir dann aber nicht auch die Schicht irgendwo speichern, welche wir geändert haben? Sonst sagen die User "Ich weiß gar nicht mehr was da geplant war!". Oder ist das wieder ein zu weit gedachter Sonderfall?

> Die meisten werden froh sein, wenn irgendwas Plausibles rauskommt, also sollten wir nicht zu viele Sonderfälle berücksichtigen bzw. zu viele Möglichkeiten geben.
:100:

> Zu den Pausen... "fair" wäre es, die Schicht zu teilen, eine Pause einzufügen und die 2. Hälfte um die Pause zu schieben.
Zum Verständnis: redest du gerade davon, dass wir die Schicht genau in der Mitte halbieren? Ich dachte, sobald eine vollständige Pause rein passt (30 Minuten bei z.B. 7h30m Arbeitszeit), gibt es eine 6h Schicht, 30 Minuten nichts und dann nochmal eine 1h Schicht. Meintest du das auch so?

> Arbeitsrechtlich müsste die Schicht geteilt und die Pausenzeit gelöscht werden, oder? 😉

Hier kann ich nicht folgen :)

> Die Flowcharts sind super! Die müssen in die Doku... 😄
Ja, ich denke es ist sinnvoll den endgültigen Zustand dann dokumentiert zu haben.

**Comment by sheepyhollow** [comment]
> Sollten wir dann aber nicht auch die Schicht irgendwo speichern, welche wir geändert haben? 
Hmja, irgendeine Form von Protokollierung, die über das hinausgeht, was am Ende im Export steht...
Könnte man für jeden User so ein Log schreiben?Muss man sich halt eine gute Formulierung überlegen, aber

**Comment by sheepyhollow** [comment]
Fazit: kein Split, Pausenzeiten werden automatisch beim Export berechnet und abgezogen. Bzw eben auch Live im Dashboard angezeigt, aber nicht 1:1 in der Datenbank innerhalb des Schicht-Objektes dargestellt

**Comment by mimischi** [comment]
OK, damit ändert sich das Beenden der Schicht hierzu:

![finish_shift](https://user-images.githubusercontent.com/1052860/35700185-8b2841f0-0792-11e8-84f3-eae8547b2810.png).

**Comment by mimischi** [comment]
Kurzer Kommentar zum manuellen Stechen: wenn beim Start/Stop ein Überlapp mit einer schon gespeicherten Schicht bemerkt wird, wird der User weitergeleitet:

- Schicht nicht einstecken.
- Gestochene Schicht verwerfen.
- Überlappende Schicht löschen.
