### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#477]
Hier meine Kommentare zu den Punkten des DSB. Ich würde das gerne zeitnah an PS abschicken, damit wir den HiWi-Vertrag von bald fertig machen können. Falls ihr noch Änderungswünsche- oder vorschläge habt, dann bitte ich um Kommentare. Bei 3 und 5 bin ich noch etwas unsicher. 

> 1. Die Daten müssen verschlüsselt eingegeben werden können. Dazu sollte die Seite über ein offiziell signiertes Zertifkat verfügen.

Das ist technisch in jedem Fall umsetzbar und sollte mit dem Betrieb auf einem HRZ-System erst recht kein Problem sein.

> 2. Es sollte ein Datenbanksystem zur Speicherung genutzt werden, das über hinreichende Sicherheitsmerkmale verfügt (kein Excel oder Access).

Das System nutzt eine PostgreSQL-Datenbank nach aktuellen, netzüblichen Standards, so dass die entsprechenden Sicherheitsmerkmale gegeben sind.

> 3. Ein klares Rollenkonzept ist zu definieren, das genau regelt, wer auf welche Daten zugreifen kann. (Aufsichtskontrolle der Gruppenleiter. Personalabteilung etc.)

Die geplante Software is ausschließlich ein Service für Hilfskräfte zum Erfassen ihrer Stunden und zum "intelligenten" Generieren des Stundenzettels. Außer den Benutzern selbst hat niemand Zugriff auf die Daten.

Systemadministratoren können aus technischen Gründen und aus technischer Notwendigkeit Zugriff auf die Daten erlangen; dies gilt jedoch für nahezu jede Software. Es ist möglich, diesen Zugriff weiter einzuschränken oder zumindest zu erschweren, z.B. durch verschlüsselte Speicherung.

Eine Erweiterung auf die Einsichtmöglichkeiten anderer Personen (z.B. Dienstvorgesetze etc.) ist technisch möglich. Ob dies gewünscht ist muss man zu gegebener Zeit entscheiden werden wenn das Basissystem funktioniert.

> 4. Löschungsfristen sind zu definieren und automatische Löschungen vorzusehen. Diese sollten so implementiert sein, dass bei möglichen Widersprüchen oder arbeitsrechtlichen Verfahren, eine Beweissicherung möglich ist.

Die Randbedingungen (Speicher- und Löschfristen) müssen von PS vorgegeben werden. Eine technische Umsetzung dieser Fristen ist technisch möglich und wird entsprechend der Vorgaben vorgesehen.

> 5. Eine Funktion zur Ausgabe aller gespeicherten Daten einer Person ist zu realisieren, die zur Implementierung des Rechts aus Auskunft bzw. des Rechts auf Korrektur falscher Daten genutzt werden kann.

Diese Möglichkeit wird gegeben sein.

> 6. Funktionen zur Korrektur falscher Daten sind zu implementieren, die automatisch die Betroffenen über die Änderung der Daten informiert.

Die Software verarbeidet nur Daten, die die Benutzer selbst eingeben und werden nicht von dritter Seite (z.B. automatisch) überprüft.
Die eingegebenen Daten müssen diversen Randbedingungen genügen (im Rahmen des AZK) die bereits bei der Eingabe überprüft werden. 
Die eingegebenen Daten können grundsätzlich geändert werden. Ein prinzipielles Procedere zur Korrektur bereits eingereichter/abgelegter Stundenzettel muss allerdings von PS vorgegeben werden und wird entsprechend abgebildet.
Vorgenommene Änderungen eingegebener Daten werden dem Benutzer entsprechend transparent gemacht.

> 7. Das IT-Verfahren ist beim SMT-Team der Universität anzumelden.

Dies wird spätestens geschehen, sobald die Testphase beginnt. Zum jetzigen Entwicklungsstand wäre eine solche Anmeldung verfrüht.

> 8. Möglicherweise (bei großem Datenvolumen) ist eine Datenschutzfolgeabschätzung durchzuführen.

Von einem besonders großen Datenvolumen ist selbst bei umfassender Nutzung durch viele Benutzer nicht auszugehen.

> 9. Neben dem Impressum ist eine Datenschutzerklärung zu verfassen, die über Umfang der erfassten Daten, Zweckbestimmung, Rechtsgrundlage und Speicherfristen umfänglich informiert.

Diese wird selbstverständlich ggf. mit Unterstützung des DSB bzw. der RA verfasst.

**Comment by mimischi** [comment]
Sieht soweit gut aus.

Zu 3.:

> Systemadministratoren können aus technischen Gründen und aus technischer Notwendigkeit Zugriff auf die Daten erlangen; dies gilt jedoch für nahezu jede Software. Es ist möglich, diesen Zugriff weiter einzuschränken oder zumindest zu erschweren, z.B. durch verschlüsselte Speicherung.

Ich bin am überlegen, ob wir das nicht trotzdem vollständig anonym darstellen können im Admininterface. Sprich, wir sehen im Interface gar nicht welchem User welche Schicht gehört, sondern sehen nur die Schichten mit einer dazugehörenden ID. Andererseits sollte das mit den zuständigen Abteilungen abgesprochen sein, bevor wir anfangen unsere eigene Idee umzusetzen - eventuell ist es in diesem Fall gar nicht notwendig und deine Erklärung schon ausreichend.

Zu 5.:

Hier sollte, wie bei den anderen Antworten erwähnt werden, dass wir geforderte Vorgaben umsetzen können. Letztlich ist die Frage wie die Daten bereitgestellt werden sollen (Schichten als CSV, Profil als PDF Zusammenfassung?). Eine Ausgabe in ein x-beliebiges Format ist möglich, es sollte eben nur geklärt sein, wie das wunschgemäß aussehen soll.

**Comment by sheepyhollow** [comment]
> Ich bin am überlegen, ob wir das nicht trotzdem vollständig anonym darstellen können im Admininterface.

Naja - mein Gedanke ging eher in die Richtung, dass ein Admin, der eine Verschlüsselung implementiert, vermutlich immer einen (theoretischen) Weg kennt, diese wieder rückgängig zu machen - denn die Daten müssen ja irgendwie zuordenbar bleiben. Aber das BDSG akzeptiert als Anonymisierung auch den Fall, dass die Zuordnung nur mit erheblichem Aufwand möglich ist. Insofern ist dieser Fall safe. Ich formuliere das mal leicht um dann. Finde aber die Idee, das im Admin-Interface zu erschweren, gut.

und zu 5.: Im Moment geht es erstmal nur darum, dass wir versichern, dass wir es _können_. Wie das dann aussieht muss man eben sehen. Aber ich denke, dass wir an dieser Stelle auch unsere Idee einbringen können.

**Comment by chgad** [comment]
Zu 3.:

Alle Rollenverteilung die denkbar sind, sind möglich prinzipiell. Also was Adminrollen, EInsichts und Ausgaberechte angeht.

Zu 5.:

Soweit ich weiß ist ein **MUSS** lediglich *anzeigen*  welceh Datengespeichert werden. Allerdings stimme ich @mimischi zu, auch eine Ausgabe als Datei ist möglich, relativ einfach sogar, auch unterschiedliche FOrmat sind kein PRoblem.

**Comment by mimischi** [comment]
Da die Mail abgeschickt ist, können wir den Thread hier vorerst wieder schließen.
