### ISSUE TITLE
Fehlende Features/Bugs

### ISSUE THREAD

**Issue by mimischi** [mimischi/django-clock#61]
## UX
- [x] Die vom User gewählte Sprache wird aktuell nur mit Cookies und Sessions gespeichert. Kehrt man auf einem anderen Gerät wieder, so wird erneut die Standardsprache angezeigt. Der Wert sollte (sobald gesetzt) in der Datenbank gespeichert werden. Hierfür muss ein erweitertes User-Profil angelegt werden.
- [x] Usern die Möglichkeit geben das eigene Profil (und die dazugehörenden Daten) zu löschen.
- [x] Schichten mit Schlüssel K/U markierbar machen
- [x] Szenario: User surft Monate ohne Schicht und klickt auf "Schicht hinzufügen". Soll nun im Feld für  Start/Ende der Schicht der jeweilige Monat eingetragen werden? Eventuell wird das so erwartet zwecks Usability.
## UI
- [x] Landing-Page aktualisieren
- [ ] Design aufräumen und noch mal für mobile Geräte anpassen
## Allgemeines
- [x] Info/About-Seite
- [x] Disclaimer
- [x] Impressum
- [x] Datenschutz (?)
- [x] Kontaktformular für generelle Anfragen
- [ ] Feedback-Modul, um von bestimmten Seiten einen Bug zu reporten
- [ ] Seitenstatistik (Zugriff über Piwik), aber auch eventuell eine Auswertung aller Schichten (anonym)?
## Code-spezifisch
- [x] Referenzen zum Python-Paket boto (Amazon S3) entfernen
- [x] Redis entfernen
- [ ] Export per POST und nicht GET realisieren
- [ ] Export User input prüfen

**Comment by sheepyhollow** [comment]
Allgemeines
- Impressum, Disclaimer und Datenschutz müssen sein.
- Feedback ist für den Testbetrieb sehr hilfreich, allgemeiner Kontakt fast weniger.
- Die Statistik ist für die 1.0-Version eigentlich nicht so wichtig, könnte man etwas niedriger priorisieren.

**Comment by sheepyhollow** [comment]
Und wenn alles läuft, dann schreiben wir noch lustige Fehlermeldungen...
"...echt jetzt? 4 Minuten Pause? Bist Du ein Streber??"
"20 Minuten Schicht. Läuft heut nicht so, was?"
"8 Stunden Schicht? Gib Dir. Wenn das der Arbeitsschutz mitbekommt!"
"Ausgeclockt um 3:40. Ab ins Bett jetz."

**Comment by sheepyhollow** [comment]
Aber Spaß beiseite: Ich finde es gut, dass der "Exportieren-Button" jetzt da ist.
Aber es sollte ein Hinweis da sein, wenn er ausgegraut ist (i.e. kein Vertrag gewählt ist).
Weiß nicht, wie man das in einem responsive Design so löst, üblicherweise... Tooltip ist ja nicht unbedingt das Ding

**Comment by mimischi** [comment]
Tooltip ist geplant und mit Bootstrap möglich. Allerdings gibt es da einen Haken für ausgegraute(/disabled)-Buttons, wo man einen Trick anwenden musste. Wollte die Schicht-Seite ja noch mal vom Design überarbeiten, dann kommt das auch!

**Comment by sheepyhollow** [comment]
hmmm... Wenn's tricky ist muss es ja nicht unbedingt disabled sein. Wenn man auf eine Seite kommt (könnte man das nicht mit so einem Overlay machen?), die sagt "Vor Export Vertrag wählen" wäre das ja okay. Funktionen, die einem nicht sagen, warum sie nicht funktionieren, sind für die UX halt nicht gut - bzw. ist das eine Frage des Workflows.
