### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#65]
Im Shift Edit Modus verhält sich der das Datums/Zeitfeld komisch, wenn man manuell darin mit der Tastatur herumstellt (ohne den Picker zu benutzen).

Außerdem wäre es schöner, das Datenformat "deutsch" zu haben - oder in den Einstellungen angeben zu können. 

Langfristig fände ich eine Trennung von Tag und Zeit besser, das ist noch nicht so optimal (auch beim Definieren des Vertrags)

**Comment by mimischi** [comment]
Commit a711897b3fbbe07a44084ad3d430248f833308a3 hat die Lokalisation im Widget nun eingeführt.

**Comment by mimischi** [comment]
Fixed 8240ee64e99e92a6df86a4bb8da8cf7f283aadce.
