### ISSUE TITLE
Unterschrift als Bild

### ISSUE THREAD

**Issue by sheepyhollow** [mimischi/django-clock#97]
Könnte man die Unterschrift einscannen oder einen Weg finden, die hineinzubekommen (bräuchte dann wohl ein Minimum an Bildbearbeitung, Kontrastfilter etc.), damit man sich das Ausdrucken ganz sparen kann?

**Comment by mimischi** [comment]
Technisch ist das kein Problem (Bild hochladen, Bild an Position X/Y in PDF einfügen). Es stellen sich aber einige Fragen:

- Ist das rechtskräftig?
- Kommt mit der Aufbewahrung der Unterschrift auf einem Server irgendein bürokratischer Akt auf?
- Benötigt man die Unterschrift überhaupt? Irgendwie hat die aktuellste Version (Stand: 10 / 2015) keinen Vermerk davon, oder?

**Comment by svenk** [comment]
Ich habe Timesheets an der GU schon mit eingescannt/ausgedruckter Unterschrift gesehen. Wenn man sowas einbauen will, würde ich da rechtlich kein großes Fass aufmachen, sondern den Upload eines Bildes anbieten und es an geeigneter Stelle ausgeben. Natürlich könnte man nach dem Upload noch Optimierungen anbieten (Beschneiden, Kontrast, usw.) aber gerade für Smartphones gibts da mittlerweile auch eine Menge brauchbarer Scan-Apps die genau das übernehmen.

**Comment by mimischi** [comment]
Wie sieht es hier denn rechtlich aus mit dem Speichern einer Unterschrift auf unseren Servern? Irgendwie glaube ich, dass man damit ein riesiges Fass um das Thema Datenschutz aufmacht. Oder nicht?

**Comment by svenk** [comment]
Naja wenn du mal ein bisschen googlest, dann findet sich: Nichts. Eingescannte Unterschriften sind mal rechtsgültig, mal nicht. Mal sind sie Ausdruck einer Art Vollmacht, dann wieder nicht. Uns ist bewusst, dass es im Digitalen geeignete Möglichkeiten gibt, Echtheit zu verifizieren (etwa auf Kryptosystemen basierende digitale Unterschriften), und dass eine eingescannte Unterschrift nicht dazu zählt. Ich würde den Benutzer ehrlich daraufhinweisen, was er gerade macht (und zwar seine Unterschrift auf einen Server in der GU hochladen) und wem die Daten gehören (und zwar ihm) bzw. was damit passiert (Verfahrensverzeichnis, falls er das gerne sehen will -- ich persönlich würde einen Link zu (Github)[https://github.com/mimischi/django-clock] bevorzugen ;-) ). Erst mal einen Präzedenzfall schaffen und dann wird man ja sehen, ob eine Rechtsabteilung vorbeikommt und Fragen stellt. Und auf diese gibt es ja Antworten.

**Comment by mimischi** [comment]
Bleibt so, weil aktuell keine Unterschrift auf dem Stundenzettel benötigt wird.
